### ISSUE TITLE
Move to cibuildhweel action

### ISSUE THREAD

**Issue by tazarov** [amikos-tech/llamacpp-embedder#18]
```yaml
 - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          CIBW_ARCHS_WINDOWS: AMD64 ARM64
          CIBW_TEST_SKIP: "*-win_arm64"
```
